/**
 * Archivo: BackEnd/src\scripts\add20Products.js
 * Proposito: Define la logica principal de add20Products dentro de TechHub.
 */
import dotenv from 'dotenv'
import { sequelize } from '../config/db.js'
import { Product } from '../models/Product.js'

dotenv.config()

const newProducts = [
  {
    name: 'CableLink USB-C 240W Braided',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 39000,
    originalPrice: 59000,
    image: 'https://images.unsplash.com/photo-1580901369227-308f8fe1a7d5?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Cable trenzado EPR para carga rapida y larga vida util.',
    dealTag: 'Accesorio esencial',
  },
  {
    name: 'WireFlow Organizer Kit 12P',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 28000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Clips y canales para ordenar cables del escritorio.',
    dealTag: 'Setup limpio',
  },
  {
    name: 'DockStation Nova 11-in-1',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 169000,
    originalPrice: 239000,
    image: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80',
    featured: true,
    adminOnly: false,
    tagline: 'Hub con HDMI dual, Ethernet y lector SD para productividad.',
    dealTag: 'Top conectividad',
  },
  {
    name: 'MousePad Aero Glide XXL',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 52000,
    originalPrice: 78000,
    image: 'https://images.unsplash.com/photo-1587033411391-5d9e51cce126?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Superficie extendida anti-desgaste para teclado y mouse.',
    dealTag: 'Control total',
  },
  {
    name: 'Monitor Arm Titan Dual',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 214000,
    originalPrice: 298000,
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Brazo dual con ajuste de altura para dos monitores.',
    dealTag: 'Ergonomia pro',
  },
  {
    name: 'TypeWave 96 Hot-Swap',
    category: 'keyboards',
    categoryLabel: 'Teclado',
    price: 289000,
    originalPrice: 379000,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80',
    featured: true,
    adminOnly: false,
    tagline: 'Formato 96% con switches intercambiables y RGB por tecla.',
    dealTag: 'En tendencia',
  },
  {
    name: 'KeyForge TKL Magnetic',
    category: 'keyboards',
    categoryLabel: 'Teclado',
    price: 334000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=900&q=80',
    featured: true,
    adminOnly: false,
    tagline: 'Activacion magnetica ajustable para juego competitivo.',
    dealTag: 'Esports ready',
  },
  {
    name: 'DeskKey Silent Full',
    category: 'keyboards',
    categoryLabel: 'Teclado',
    price: 198000,
    originalPrice: 249000,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Teclado full-size silencioso para oficina y estudio.',
    dealTag: 'Trabajo diario',
  },
  {
    name: 'PulsePoint Viper 2K',
    category: 'mice',
    categoryLabel: 'Mouse',
    price: 119000,
    originalPrice: 169000,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Sensor 26K DPI y switches opticos de larga duracion.',
    dealTag: 'Precision gamer',
  },
  {
    name: 'ErgoTrack Vertical Plus',
    category: 'mice',
    categoryLabel: 'Mouse',
    price: 136000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Diseno vertical para reducir fatiga en jornadas largas.',
    dealTag: 'Confort diario',
  },
  {
    name: 'SwiftAim Air Wireless',
    category: 'mice',
    categoryLabel: 'Mouse',
    price: 175000,
    originalPrice: 229000,
    image: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?auto=format&fit=crop&w=900&q=80',
    featured: true,
    adminOnly: false,
    tagline: 'Mouse ultraligero inalambrico con 70 horas de bateria.',
    dealTag: 'Ultra ligero',
  },
  {
    name: 'SoundCore Orbit 7.1',
    category: 'headsets',
    categoryLabel: 'Audifono',
    price: 247000,
    originalPrice: 329000,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Sonido envolvente virtual 7.1 y microfono desmontable.',
    dealTag: 'Inmersion total',
  },
  {
    name: 'VoicePro Studio USB-C',
    category: 'headsets',
    categoryLabel: 'Audifono',
    price: 312000,
    originalPrice: 419000,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80',
    featured: true,
    adminOnly: false,
    tagline: 'Perfil balanceado para streaming, reuniones y edicion.',
    dealTag: 'Creator audio',
  },
  {
    name: 'CloudTune Lite ANC',
    category: 'headsets',
    categoryLabel: 'Audifono',
    price: 189000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Cancelacion activa de ruido con almohadillas memory foam.',
    dealTag: 'Viaje y oficina',
  },
  {
    name: 'ViewMax 25 IPS 180Hz',
    category: 'monitors',
    categoryLabel: 'Monitor',
    price: 612000,
    originalPrice: 739000,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Monitor rapido de 180Hz con excelente cobertura sRGB.',
    dealTag: 'Smooth visual',
  },
  {
    name: 'PixelFrame 27 QHD HDR',
    category: 'monitors',
    categoryLabel: 'Monitor',
    price: 899000,
    originalPrice: 1089000,
    image: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?auto=format&fit=crop&w=900&q=80',
    featured: true,
    adminOnly: false,
    tagline: 'Resolucion QHD con HDR para trabajo visual y gaming.',
    dealTag: 'Calidad premium',
  },
  {
    name: 'UltraDesk 29 WFHD Curvo',
    category: 'monitors',
    categoryLabel: 'Monitor',
    price: 724000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Formato 21:9 para multitarea sin doble monitor.',
    dealTag: 'Productividad',
  },
  {
    name: 'EtherLink Cat8 2m',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 26000,
    originalPrice: 38000,
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Cable de red Cat8 para baja latencia y alta velocidad.',
    dealTag: 'Red estable',
  },
  {
    name: 'PowerStrip Surge 8',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 67000,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1601944179066-29786cb9d32a?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Regleta con proteccion de picos y 8 salidas AC.',
    dealTag: 'Proteccion setup',
  },
  {
    name: 'CamMount Desk Clamp',
    category: 'accessories',
    categoryLabel: 'Accesorio',
    price: 83000,
    originalPrice: 119000,
    image: 'https://images.unsplash.com/photo-1616628188550-808682f40f23?auto=format&fit=crop&w=900&q=80',
    featured: false,
    adminOnly: false,
    tagline: 'Soporte de escritorio para webcam o luz de streaming.',
    dealTag: 'Streaming kit',
  },
]

// run: coordina este flujo principal del modulo.
async function run() {
  try {
    await sequelize.authenticate()
    const created = await Product.bulkCreate(newProducts)
    console.log(`Productos insertados: ${created.length}`)
  } catch (error) {
    console.error('Error insertando productos:', error.message)
    process.exitCode = 1
  } finally {
    await sequelize.close()
  }
}

run()

