CREATE DATABASE IF NOT EXISTS techhub_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE techhub_db;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(140) NOT NULL,
  category VARCHAR(50) NOT NULL,
  categoryLabel VARCHAR(60) NOT NULL,
  price INT NOT NULL,
  originalPrice INT NULL,
  image TEXT NOT NULL,
  featured TINYINT(1) NOT NULL DEFAULT 0,
  adminOnly TINYINT(1) NOT NULL DEFAULT 0,
  tagline VARCHAR(255) NOT NULL,
  dealTag VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
